### ISSUE TITLE
Roadmap for rOpenSci submission

### ISSUE THREAD

**Issue by Rekyt** [Rekyt/rromeo#22]
- [X] Higher test coverage (see #7)
- [X] pkgdown website
- [X] Improved README showing basic functionality
- [ ] Full vignette & analysis on Ecological journals
- [x] Software LICENSE information
- [x] CONTRIBUTING information
- [x] Recheck rOpenSci book for package submission https://ropensci.github.io/dev_guide/
- [x] Add `codemeta.json` information
- [x] Add `package` help page (use `usethis::use_package_doc()`)
- [x] Add package dependency graph at the bottom of `README.Rmd`
- [ ] Provide license for the data API (see #29)
